server:
  port: 5000

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri:
            lb://USER-SERVICE
          predicates:
            - Path=/auth/**, /users/**, /api/users/**, /
        - id: INTERNSHIP-REGISTRATION-SERVICE
          uri:
            lb://INTERNSHIP-REGISTRATION-SERVICE
          predicates:
            - Path=/api/internship-registration/**
        - id: APPROVAL-SERVICE
          uri:
            lb://APPROVAL-SERVICE
          predicates:
            - Path=/api/approvals/**, /
        - id: STUDENT-SERVICE
          uri:
            lb://STUDENT-SERVICE
          predicates:
            - Path=/api/students/**, /

      default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka