server:
  port: 5002

spring:
  application:
    name: INTERNSHIP-REGISTRATION-SERVICE
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/internship_registration_service
    username: root
    password: duc432003
    driver-class-name: com.mysql.cj.jdbc.Driver